lib/cob_index/indexer_config.rb, lib/cob_index/macros/custom.rb, spec/fixtures/marc_files/title_statement_examples.xml, spec/traject_indexer_spec.rb
When no title is found using the minimal selection of 245 sub fields,
then create a title from all the sub fields a through z.
=> [BL-831] Use all the 245 fields when no title is found.

lib/cob_index/indexer_config.rb, lib/cob_index/macros/custom.rb, lib/translation_maps/shelf_map.properties
- Removes the following fields that we are not using: 
- lc_callnum_display
- lc_1letter_facet
- lc_alpha_facet
- lc_b4cutter_facet
- library_location_display
- diamond_id_display
- The library_location_display field was created as part of the twilio integration that we did not end up using.  This also removes the custom extract method and translation file related to the unused field
=> BL-974 Remove unused fields from Traject

lib/cob_index.rb, lib/cob_index/dot_properties.rb, spec/cob_index/dot_properties_spec.rb
Allow use of our dot_properties config so that we don't have to maintain
these files across multiple repositories.
=> Add dot_properties wrapper.

lib/cob_index/indexer_config.rb, lib/cob_index/solr_json_writer.rb, spec/cob_index/solr_json_writer_spec.rb
Closes #28
Allow logging of 409 errors but do not include them in calculus to error
out the ingest process. This makes it possible to enable versioning on
solr while still monitoring when a record gets rejected to the
versioning control.
=> Do not error out on 409.

lib/cob_index/solr_json_writer.rb, spec/cob_index/solr_json_writer_spec.rb
When Solr versioning is enabled the default traject json writer often
has to break up the batched update into many single updates do to Solr
responding with 409 errors.
This commit adds a configurable optimization option which when enabled
will make a call to Solr to find the record update dates of records that
are about to be batched processed. Then it uses this information to
filter out the batched records if they are older than the Solr records.
Thus, we avoid Solr responding with 409 and avoid breaking up the
batched update into many single updates.
The reason this is configurable is because we wouldn't need or want to
do this for full re-indexing jobs which would happen on a clean Solr
collection.
This optimization does not guarantee to work when multiple workers are
indexing …
=> Add configurable optimization for versioned batched updates.

lib/cob_index/macros/custom.rb, lib/cob_index/solr_json_writer.rb, spec/cob_index/macros/custom_spec.rb
- The new library website uses /finding_aids instead of /scrc.
- We need to have logic for both the old and new cases right now, so this adds an or statement to the extract_url_finding_aid method and the extract_url_more_links
- Also fixes a typo
=> BL-1030 Finding aids logic

README.md, exe/cob_index, lib/cob_index.rb, lib/cob_index/indexer_config.rb, spec/cob_index_spec.rb
What this PR attempts:
- removing commits being issued by the client. 
Questions related to this PR:
- this just manually changes this; should they be a flag, config value, or other? does such a flag or envvar exist that I can pass in with the cli (sorry if I missed it)
- we *may* be okay with ignoring this for the time being, though it is generally recommended in the solrcloud docs / discussions i've had to let solrcloud use its own autocommit settings.
Would appreciate feedback or thoughts on this PR about how to best proceed.
=> Removing Commits from Client

.travis.yml, lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb, spec/fixtures/marc_files/library_facet.xml
- Use ITM field instead of HLD field to retrieve library. 
- Will not include libraries with missing or lost items, in addition to items in RES_SHARE
- Returns library names only once
- Adds tests for this method
=> BL-897 Refactor library_facet field

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb
- The original finding aids/more links logic was developed using http addresses.
- Since the library now uses https, we need to add that logic in.
- Some of the old records still have http, so we need to handle both instances.
=> BL-1101 Finding aids logic

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb, spec/fixtures/marc_files/lost_missing_technical.xml
- Records should be suppressed if they have no HLD or PRT fields as long as there is also no 856["u"] present
=> BL-1049 Suppress empty records

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb
- Our translation only worked for 650["a"] if there was no punctuation.  
- This trims punctuation first so that all necessary values are translated to the desired value
=> BL-1056 Subject headings update

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb
- We need to keep punctuation when a field is not translated.  
- This updates the method and adds a test
=> BL-1056 Subject headings

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb, spec/fixtures/marc_files/lost_missing_technical.xml
- We are currently suppressing lost/missing items when there is only 1 item
- This updates the method to check whether all of item subfield["u"] are lost/missing and suppresses them
=> BL-1148 Suppress records when all items are lost/missing/etc.

lib/cob_index/indexer_config.rb, lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb, spec/fixtures/marc_files/oclc.xml
Adds a csv file in `lib/hathi_data_overlap.csv` that contains oclc
number and Hathi Trust bib_key for physical items in the Temple
collection that have been digitized by Hathi and are available under the
temporary emergency access program.
This change causes traject to search (grep) the overlap.csv file for the
records oclc number. If it returns nothing, no record is created. If it
matches, it returns a string with "bib_key,oclc_num".
This will slow down the indexing process as grepping a 12MB file takes
~.35 seconds, which is substantally slower than a usual traject processing task. We could optimize if needed, but I wanted to get a first pass in for other to look at.
I've written up a rough sketch of the[ process for creating the overlap csv …
=> Add hathi_bib_key_display for relvant items

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb, spec/fixtures/marc_files/lost_missing_technical.xml
We errored out in production when a MARC record contained a malformed 902. This makes that method a little safer.
=> Make supression logic a little safer.

lib/cob_index/nokogiri_indexer.rb
The get_id method assumed all mms_ids are 18 digits long and if not was
returning nil for the id.
=> Fix harvest fails when mms_id not exactly 18 digits long.

lib/cob_index/macros/custom.rb, spec/cob_index/macros/normalize_lccn_spec.rb
- Updates the normalize_lccn method to only return the normalized lccn numbers
- Adds tests 
- Substitutes an empty space for the # symbol because the normalizer doesn't handle that edge case
=> BL-1175 Normalize LCCN numbers

exe/cob_index
* Without arg_name command fails if it requires an argument
=> Add back required arg_name for commands.

lib/cob_index/indexer_config.rb, lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb
Processes lc call numbers into codes that will sort correctly in solr. 
Note that the real tests are in tul_cob/indices_spec.rb. Perhaps it would make sense at some point to add integration tests that use solr?
=> BL-1165-lc-call-number-sort

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb
=> zap duplicate subfields in call number, preserve spacing

lib/translation_maps/locations.yaml
Previously, we prepended "Remote Storage," to external name that was defined in Alma. However, some of external location names have been updated such that it's no longer necessary. @htomren can you review this PR and confirm that this looks okay? The govs doc, media, and micro locations now do not "Remote Storage" in the label (which is consistent with Alma). I'm okay with this since they aren't as confusing as the other locations in Remote that are defined by library.
=> BL-1386 Update Remote Storage location labels

Gemfile, Gemfile.lock
* The mimemagic gem v0.3.5 has been yanked.
=> Update mimemagic gem.

lib/cob_index/indexer_config.rb
- We are indexing the same genre mapping for three different fields
- This removes the _display and _facet fields, but keeps the _t field so that we get the correct solr configurations
=> BL-1319 Remove extra genre fields

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb
* The current indexing job is adding relation fields when it shouldn't
be. This change updates code to fix that bug.
* This code also skips indexing fields with no title.
=> BL-1514: Add title relation only for 246 fields.

lib/translation_maps/donor_info.yaml
- Fix donor name typo
This is not a rush, but can be incorporated into the next full reindex.
=> Fix donor name typo

lib/cob_index.rb, lib/cob_index/indexer_config.rb, lib/cob_index/macros.rb, lib/cob_index/macros/transformations.rb, spec/cob_index/macros/transformations_spec.rb
* Adds new filter_stop_words macro that removes list of supplied values
from the final accumulation of field values.
* Updates field creator_facet indexing definition to add a list of
values to filter.
* Adds test for new macro;
* A little cleanup in order to add macro (plus setup for future
cleanup).
=> BL-255: Remove some corporate names from creator_facet values.

lib/cob_index.rb
Versioning is set up as a monkey-patch not via included module.
=> Fix undefined VERSION

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb
* Does not assume "reverse" order when sorting breaks.
* Adds correct sorting criteria.
* Tests that sorting works for specified criteria.
=> BL-300: Fix broken sorts for electronic resources.

lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb
- Updates the names of the electronic resource subfields to better reflect what they are
- Refactors code to get dates from the coverage_statement instead of the availability field
=> BL-300 Sorting electronic resources

lib/cob_index/indexer_config.rb, lib/cob_index/macros/custom.rb, spec/cob_index/macros/custom_spec.rb, spec/fixtures/marc_files/title_statement_examples.xml
* Adds new fields (title_with_subtitle_display,  responsibility_display, title_with_subtitle_vern_display, responsibility_vern_display, title_with_subtitle_truncated_display, and responsibility_truncated_display)
* Strips trailing slash and whitespace when a subfield "c" is present
* Updates specs to match new expectations
* For now, leaving the old title_statement fields in the code.  They will be removed as part of future work.
=> BL-1701 Adds new fields related to title_statement updates

lib/cob_index.rb, lib/cob_index/indexer_config.rb, lib/cob_index/macros.rb, lib/cob_index/macros/booster.rb, lib/cob_index/macros/custom.rb, spec/cob_index/macros/booster_spec.rb
Adds new macro for boosting based on labels.
Adds label for inverse boosting on bad_libraries label.
Adds label for inverse boosting on bookseller label.
=> BL-1731: Add generic booster.

lib/cob_index/indexer_config.rb, lib/cob_index/macros.rb, lib/cob_index/macros/custom.rb, lib/cob_index/macros/wrapper.rb, spec/cob_index/indexer_config_spec.rb, spec/cob_index/macros/custom_spec.rb, spec/cob_index/macros/wrapper_spec.rb
* The flank macro is used to add a token to the beginning  and end of a
string that is going to be indexed. But, with the version this change 
fixes, that token is always the same and for Solr tokenizers that split on 
white spaces it's essentially lost in the shuffle (just another token).
By updating the macro to create a token that embeds more information about
what exactly a string begins with and a string endswith we can include the
specific token to pull the desired results.
* Moves flank/wrapper methods to new module to use in tul_cob.
``
=> Refactor flank macro.

lib/cob_index/macros/wrapper.rb
This will make it so I don't have to repeat the check for empty string
or the matcher when using the  method from tul_cob.
=> Add and use add_first_word_matcher, add_last_word_matcher.

lib/cob_index/cli.rb, spec/cob_index_spec.rb
The delete command only seems to work when is used as supress not when it's used to delete.
This changes fixes the file not found error when it is not used to supress.
=> Fix delete command not working.

lib/cob_index/macros/subject.rb, lib/translation_maps/subject_remediation.yaml, spec/cob_index/macros/subject_spec.rb
* Normalizes subjects before translation to handle casing issues
* Removes subfield $0 from displaying
* Removes marc 043 from displaying
* Adds additional translations to map
=> BL-1943 Updates methods related to new subject translations
