bin/massage.sh

Needed for pre-indexing XML manipulation

Move massage.sh from tul_cob bin

---

lib/cob_index/macros/custom.rb
spec/cob_index/macros/custom_spec.rb

- We need to index PRT subfield f to get the portfolio level public notes

Bl 1004 add public note

---

lib/cob_index/macros/custom.rb
spec/cob_index/macros/custom_spec.rb

Update the way we display illegal aliens and variants for subject displays.

Update subject display for field 650, subfield a

---

lib/cob_index/macros/custom.rb

Fix syntax error in subject_translations

BL-1056 Subject headings

---

lib/cob_index/macros/custom.rb
spec/cob_index/macros/custom_spec.rb
spec/fixtures/marc_files/oclc.xml

- strip leading zeroes from oclc numbers

BL-1153 update oclc_number-display

---

Gemfile.lock
lib/cob_index.rb

* Updates alma_rb to version that fixes timeout issues.
* Increases the timeout for requests to 300 seconds.
* Uses default retry (3)

Increase request timeout.

---

exe/cob_index

switches are only true or false, but flags can have any string value.

Make harvest --type a flag.

---

lib/cob_index/macros/custom.rb

Fixes fail can't find file when invoked from outside cob_index repo dir.

Look in gem's path for data.

---

lib/cob_index/macros/custom.rb
spec/cob_index/macros/custom_spec.rb
spec/fixtures/marc_files/lost_missing_technical.xml

- A recent change resulted in purchase order titles being suppressed.  This updates the logic so that those records are included in the indexing process.

BL-1182 Bug with purchase order records

---

README.md

Documentation update to readme intro
I'm not 100% sure if this should be merged to qa or master.

Update readme introduction

---

lib/cob_index/macros/custom.rb
spec/cob_index/macros/custom_spec.rb

* Skips ingesting record when all the items are inactive.

BL-1222: Supress record when all its items are inactive.

---

Gemfile
Gemfile.lock
README.md

DEVO-221 Change master to main

---

lib/cob_index/macros/custom.rb
spec/cob_index/macros/custom_spec.rb

* Skips ingesting record when all the items are Not Available.

BL-1222: Supress record when all its items are Not Available

---

README.md
exe/cob_index
lib/cob_index.rb
spec/cob_index_spec.rb

* Adds missing commit command
* Updates some command description verbiage.
* Documents some environment variable behavior.

Add missing commit command.

---

README.md
exe/cob_index
lib/cob_index.rb
lib/cob_index/delete_config.rb
lib/cob_index/suppress_config.rb
spec/cob_index_spec.rb

Add suppression feature to delete command  using switch.

---

lib/cob_index/suppress_config.rb
spec/cob_index/suppress_config_spec.rb

* Fixes the config.
* Adds spec for new config.

Fix suppress config not working.

---

lib/cob_index/indexer_config.rb
lib/cob_index/macros/custom.rb
spec/cob_index/macros/custom_spec.rb

We need this to create our library/location pivot table.

BL-1052: Index new location_facet field.

---

lib/cob_index/macros/custom.rb
lib/translation_maps/locations.yaml
spec/cob_index/macros/custom_spec.rb

REQUIRES RE-INDEX
* Manage location translation at indexing.
* Collapse ASRS library locations to ASRS
* Add more filters for items that should not be indexed/counted

BL-1052: Update location_facet indexing.

---

lib/cob_index/indexer_config.rb
spec/cob_index/indexer_config_spec.rb

BL-1334: Extract subfield 050a for LC facets.

---

lib/cob_index/indexer_config.rb

- Adds new display field for lc call numbers

BL-1350 LC display field

---

lib/cob_index/indexer_config.rb
lib/cob_index/macros/custom.rb
spec/cob_index/indexer_config_spec.rb
spec/cob_index/macros/custom_spec.rb

Resolves commentary on issue:
https://tulibdev.atlassian.net/browse/BL-1334

only use 050 for call number if 090 is missing

---

.circleci/config.yml
.docker/solr/Dockerfile
.env
Makefile
bin/load-data
docker-compose.yml

Adds automatic relevancy tests to the circleci workflow.

DEVO-404: Run relevancy tests.

---

lib/cob_index/indexer_config.rb
lib/translation_maps/donor_info.yaml
spec/cob_index/indexer_config_spec.rb

* Add donor_inf_display field
* Use built-in translation mechanism to transform mmsid to donor_info

BL-1524: Index donor info display field.

---

lib/translation_maps/donor_info.yaml
spec/cob_index/indexer_config_spec.rb

- Removed selected names from donor list.
Note: I don't know why the file comparison is comparing against the original stub record instead of the latest version of the file with the fuller list of names. If I did something wrong and need to redo this, please let me know!

BL-1525: Update donor names file to remove selected names

---

lib/cob_index/macros/marc_format_classifier.rb
spec/fixtures/marc_files/integrating_resources.xml
spec/macros/marc_format_classifier_spec.rb

- Do not map integrating resources to serial if  Leader/07 is "i" and 008/21 is not "d" or "w"
- map integrating resources to book instead

BL-1546 Integrating resources format

---

lib/cob_index/macros/custom.rb
spec/cob_index/macros/custom_spec.rb
spec/fixtures/marc_files/donor_541_field.xml

- Updates mapping to allow for records with no subfield a

BL-1549 Donor field mapping

---

lib/cob_index/indexer_config.rb

- Removes 588a from the notes mapping

BL-1624 Notes mapping update

---

lib/cob_index/indexer_config.rb

- Updates collection_display to collection_ms so that it can be used as a search link

BL-251 Collection name facet

---

lib/cob_index/indexer_config.rb
lib/cob_index/macros/custom.rb
spec/cob_index/indexer_config_spec.rb
spec/cob_index/macros/custom_spec.rb

* apply delete_if macro to contributor/creator fields.
* Add specs to test delete_if macro on creator/contirubor fields.

BL-1686: Delete auther value if corporation.

---

lib/cob_index/macros/custom.rb
spec/cob_index/macros/custom_spec.rb
spec/fixtures/marc_files/extract_marc_subfield_limit.xml

Updating logic based on feedback from Holly (and simplifying code in process!)

BL-1742 Fix extract_marc_subfield_limit logic

---

lib/cob_index/indexer_config.rb
lib/cob_index/macros/subject.rb
spec/cob_index/macros/subject_spec.rb

* Adds a new solr_search_facet field that includes both deprecated and remediated terms for queries only.

Bl 1944 update subject marc tags
